### PR TITLE
read me

### PR DESCRIPTION
**Pull request by claire2d2**

### CODE REVIEW

**Comment by ivston** [comment]
Maybe make it so that links open a new tab

add login in next steps?

Otherwise looking greatt!

**Review by smnraphael — COMMENTED** [review]
You can add this to features:

Listing all the first 3 generations of Pokémon (Bulbasaur to Deoxys)
Add Pokémon to favorite
Filter Pokémon by name, height, weight, favorite
Sort Pokémon by name, generation, type, color
Create your team of Pokémon:
- Choose a Pokémon or ask for a random Pokémon
- Make it shiny
- Edit a created team
Take pictures with your existing team(s):
- Choose your trainer, team, background
PokeQuiz:
- Quiz to guess the Pokémon (MCQ)
- Train quizz / Score quiz
Mobile responsive
Dark mode

**Review by smnraphael — CHANGES_REQUESTED** [review]
You can add this to features:

Listing all the first 3 generations of Pokémon (Bulbasaur to Deoxys)
Add Pokémon to favorite
Filter Pokémon by name, height, weight, favorite
Sort Pokémon by name, generation, type, color
Create your team of Pokémon:

Choose a Pokémon or ask for a random Pokémon
Make it shiny
Edit a created team
Take pictures with your existing team(s):
Choose your trainer, team, background
PokeQuiz:
Quiz to guess the Pokémon (MCQ)
Train quizz / Score quiz
Mobile responsive
Dark mode

**Review by smnraphael — APPROVED** [review]
nice

**Pull request merged**
